### ISSUE TITLE
Max-age exception when using https (could be the same as #95 ?)

### ISSUE THREAD

**Issue by jeop10** [zendframework/zend-http#118] opened 2017-03-12 11:40 UTC
Hello I have been playing with the zend-feed with zend-http (release-2.6.0) library to read some feeds on the internet, and it all goes well until I change the domain of the feed to go with https instead of http. Then I receive this error message 

` [Zend\Http\Header\Exception\InvalidArgumentException]   Invalid Max-Age number specified`

From the little debug I did I manage to find that when setting the Max-Age a null value is given to this function, therefore a exception is thrown. But I can't seem to go any deeper to know why exactly this null value is given. 

It's the same outcome described here #95

In order to fix the issue with the zend-feed I just use the function 

`Reader::importRemoteFeed`

Which give me option to pass it a custom http client. 

Hope this help a little and sorry about my bad english.

**Comment by samsonasik** [comment] 2017-04-06 09:04
I've create PR https://github.com/zendframework/zend-http/pull/120 for it

**Comment by Xerkus** [comment] 2017-10-13 11:56
Duplicate of #95

**Closed by Xerkus** 2017-10-13 11:56 UTC
